version: '3.8'
services:
  laravel-app:
    build:
      context: "."
      dockerfile: docker/8.3-prod/Dockerfile
      args:
        WWWGROUP: "1000"
    image: "laravel-prod:latest"
    container_name: "${APP_ABBREVIATION:-laravel-app}-${APP_PORT:-3000}"
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3000}:80"
    environment:
      WWWUSER: "1000"
      WWWGROUP: "1000"
      LARAVEL_SAIL: 0
      # Application Settings
      APP_NAME: "${APP_NAME}"
      APP_ENV: "${APP_ENV:-production}"
      APP_KEY: "${APP_KEY}"
      APP_DEBUG: "${APP_DEBUG:-false}"
      APP_TIMEZONE: "${APP_TIMEZONE:-UTC}"
      APP_URL: "${APP_URL}"
      APP_LOCALE: "${APP_LOCALE:-en}"
      APP_FALLBACK_LOCALE: "${APP_FALLBACK_LOCALE:-en}"
      APP_FAKER_LOCALE: "${APP_FAKER_LOCALE:-en_US}"
      APP_MAINTENANCE_DRIVER: "${APP_MAINTENANCE_DRIVER:-file}"
      BCRYPT_ROUNDS: "${BCRYPT_ROUNDS:-12}"
      # Database Settings
      DB_CONNECTION: "${DB_CONNECTION:-mysql}"
      DB_HOST: "${DB_HOST:-host.docker.internal}"
      DB_PORT: "${DB_PORT:-3306}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      # Session Settings
      SESSION_DRIVER: "${SESSION_DRIVER:-database}"
      SESSION_LIFETIME: "${SESSION_LIFETIME:-120}"
      SESSION_ENCRYPT: "${SESSION_ENCRYPT:-false}"
      SESSION_PATH: "${SESSION_PATH:-/}"
      SESSION_DOMAIN: "${SESSION_DOMAIN}"
      # Cache Settings
      CACHE_STORE: "${CACHE_STORE:-database}"
      CACHE_PREFIX: "${CACHE_PREFIX}"
      # Queue Settings
      QUEUE_CONNECTION: "${QUEUE_CONNECTION:-database}"
      BROADCAST_CONNECTION: "${BROADCAST_CONNECTION:-log}"
      # Storage Settings
      FILESYSTEM_DISK: "${FILESYSTEM_DISK:-local}"
      # Logging Settings
      LOG_CHANNEL: "${LOG_CHANNEL:-stack}"
      LOG_STACK: "${LOG_STACK:-single}"
      LOG_DEPRECATIONS_CHANNEL: "${LOG_DEPRECATIONS_CHANNEL}"
      LOG_LEVEL: "${LOG_LEVEL:-debug}"
      # Mail Settings
      MAIL_MAILER: "${MAIL_MAILER:-smtp}"
      MAIL_HOST: "${MAIL_HOST}"
      MAIL_PORT: "${MAIL_PORT:-1025}"
      MAIL_USERNAME: "${MAIL_USERNAME}"
      MAIL_PASSWORD: "${MAIL_PASSWORD}"
      MAIL_ENCRYPTION: "${MAIL_ENCRYPTION}"
      MAIL_FROM_ADDRESS: "${MAIL_FROM_ADDRESS}"
      MAIL_FROM_NAME: "${MAIL_FROM_NAME}"
      # AWS Settings
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION:-us-east-1}"
      AWS_BUCKET: "${AWS_BUCKET}"
      AWS_USE_PATH_STYLE_ENDPOINT: "${AWS_USE_PATH_STYLE_ENDPOINT:-false}"
      # Vite Settings
      VITE_APP_NAME: "${VITE_APP_NAME}"
      # Search Settings
      SCOUT_DRIVER: "${SCOUT_DRIVER:-meilisearch}"
      MEILISEARCH_HOST: "${MEILISEARCH_HOST}"
      MEILISEARCH_NO_ANALYTICS: "${MEILISEARCH_NO_ANALYTICS:-false}"
      # Custom API Settings
      AAKASH_API_TOKEN: "${AAKASH_API_TOKEN}"
      AAKASH_API_URL: "${AAKASH_API_URL}"
      BASE_URL: "${BASE_URL}"
      ENABLED_MODULES: "${ENABLED_MODULES}"
      # Redis Settings (if needed)
      REDIS_CLIENT: "${REDIS_CLIENT:-phpredis}"
      REDIS_HOST: "${REDIS_HOST:-redis}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_PORT: "${REDIS_PORT:-6379}"
      # Memcached Settings
      MEMCACHED_HOST: "${MEMCACHED_HOST:-127.0.0.1}"
    volumes:
      # Bind mount to specific host paths for persistent storage
      - "/mnt/data/digital-epalika/${APP_ABBREVIATION}/storage/app:/var/www/html/storage/app"
      - "/mnt/data/digital-epalika/${APP_ABBREVIATION}/storage/logs:/var/www/html/storage/logs"
      - "/mnt/data/digital-epalika/${APP_ABBREVIATION}/storage/framework:/var/www/html/storage/framework"
      - "/mnt/data/digital-epalika/${APP_ABBREVIATION}/bootstrap/cache:/var/www/html/bootstrap/cache"
      # For publicly accessible uploaded files/images
      - "/mnt/data/digital-epalika/${APP_ABBREVIATION}/public/storage:/var/www/html/public/storage"
    networks:
      - laravel-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  laravel-network:
    driver: bridge
