<?php return [
    'initialRecommendation.recommendation_category_id' => 'recommendation-initialRecommendation.recommendation_category_id-field',
    'initialRecommendation.form_id' => 'recommendation-initialRecommendation.form_id-field',
    'department-{{ $id }}' => 'recommendation-department-{{ $id }}-field',
    'department-{{ $id }}' => 'recommendation-department-{{ $id }}-field',
    'recommendation_category_id' => 'recommendation-recommendation_category_id-field',
    'recommendation_id' => 'recommendation-recommendation_id-field',
    'fiscal_year_id' => 'recommendation-fiscal_year_id-field',
    'bill' => 'recommendation-bill-field',
    'rejectionReason' => 'recommendation-rejectionReason-field',
    'search' => 'recommendation-search-field',
    'filter_status' => 'recommendation-filter_status-field',
    'filter_ward' => 'recommendation-filter_ward-field',
    'filter_year' => 'recommendation-filter_year-field',
    'filter_recommendation' => 'recommendation-filter_recommendation-field',
    'filter_recommendationCategory' => 'recommendation-filter_recommendationCategory-field',
    'start_date' => 'recommendation-start_date-field',
    'end_date' => 'recommendation-end_date-field',
];
