<?php

return [
    [
        'module' => 'grievance',
        'route' => 'admin.grievance.index',
        'icon' => 'bx bx-message-dots text-danger',
        'logo' => 'GunasoByabasthapanIcon.png',
        'label' => 'Grievance',
        'perm' => 'grievance access',
    ],
    [
        'module' => 'recommendation',
        'route' => 'admin.recommendations.dashboard',
        'icon' => 'bx bx-notepad text-info',
        'logo' => 'YojanaByabasthapanIcon.png',
        'label' => 'Recommendation',
        'perm' => 'recommendation access',
    ],
    [
        'module' => 'token',
        'route' => 'admin.token_dashboard.dashboard',
        'icon' => 'bx bx-detail text-secondary',
        'logo' => 'RajaswaSankalanIcon.png',
        'label' => 'Token Management System',
        'perm' => 'token access',
    ],
    [
        'module' => 'meeting',
        'route' => 'admin.meetings.dashboard',
        'icon' => 'bx bx-calendar-event text-success',
        'logo' => 'BaithakByabasthapanIcon.png',
        'label' => 'Meeting',
        'perm' => 'meeting_access',
    ],
    [
        'module' => 'digital_board',
        'route' => 'admin.digital_board.index',
        'icon' => 'bx bx-tv text-primary',
        'logo' => 'NagarikWadapatraIcon.png',
        'label' => 'Digital Citizen Board',
        'perm' => 'digital_board access',
    ],
    [
        'module' => 'task_tracking',
        'route' => 'admin.task-tracking.index',
        'icon' => 'bx bx-list-check text-warning',
        'logo' => 'GharNaksaPassIcon.png',
        'label' => 'Task Tracking',
        'perm' => 'tsk_management access',
    ],
    [
        'module' => 'patrachar',
        'route' => 'admin.file_records.manage',
        'icon' => 'bx bx-folder',
        'logo' => 'SifarisIcon.png',
        'label' => 'Patrachar',
        'perm' => null,
    ],
    [
        'module' => 'register',
        'route' => 'admin.register_files.dashboard',
        'icon' => 'bx bx-book text-purple',
        'logo' => 'DartaChalaniIcon.png',
        'label' => 'Darta /Chalani',
        'perm' => 'darta access',
    ],
    [
        'module' => 'business_registration',
        'route' => 'admin.business-registration.index',
        'icon' => 'bx bx-briefcase',
        'logo' => 'KaryaByabasthapanIcon.png',
        'label' => 'Business Registration System',
        'perm' => 'business_registration access',
    ],
    [
        'module' => 'ebps',
        'route' => 'admin.ebps.index',
        'icon' => 'bx bx-barcode text-primary',
        'logo' => 'GharNaksaPassIcon.png',
        'label' => 'EBPS System',
        'perm' => 'ebps access',
    ],
    [
        'module' => 'plan',
        'route' => 'admin.plan.index',
        'icon' => 'bx bx-map text-success',
        'logo' => 'YojanaByabasthapanIcon.png',
        'label' => 'Plan Management System',
        'perm' => 'plan access',
    ],
    [
        'module' => 'grant',
        'route' => 'admin.grant_management.index',
        'icon' => 'bx bx-dollar-circle',
        'logo' => 'RajaswaSankalanIcon.png',
        'label' => 'Grant Management System',
        'perm' => 'gms_grant access',
    ],
    [
        'module' => 'fuel',
        'route' => 'admin.fuel.dashboard',
        'icon' => 'bx bx-gas-pump text-primary',
        'logo' => 'AnudaanByabasthapanIcon.png',
        'label' => 'Fuel Management System',
        'perm' => null,
    ],
    [
        'module' => 'ejalash',
        'route' => 'admin.dashboard.dashboard',
        'icon' => 'bx bx-book text-orange',
        'logo' => 'NyayikSamitiIcon.png',
        'label' => 'Ejalash System',
        'perm' => 'jms access',
    ],
];
