<?php return [
    'settings.mail' => 'grievance-settings.mail-field',
    'settings.sms' => 'grievance-settings.sms-field',
    'settings.fcm' => 'grievance-settings.fcm-field',
    'grievanceDetail.assigned_user_id' => 'grievance-grievanceDetail.assigned_user_id-field',
    'uploadedImage' => 'grievance-uploadedImage-field',
    'dept_{{ $department[' => 'grievance-dept_{{ $department[-field',
    '{{ $department[' => 'grievance-{{ $department[-field',
    'customer_id' => 'grievance-customer_id-field',
    'uploadedImage' => 'grievance-uploadedImage-field',
    'search' => 'grievance-search-field',
    'filter_status' => 'grievance-filter_status-field',
    'filter_priority' => 'grievance-filter_priority-field',
    'filter_ward' => 'grievance-filter_ward-field',
    'filter_year' => 'grievance-filter_year-field',
    'filter_type' => 'grievance-filter_type-field',
    'start_date' => 'grievance-start_date-field',
    'end_date' => 'grievance-end_date-field',
    'search' => 'grievance-search-field',
    'filter_status' => 'grievance-filter_status-field',
    'filter_priority' => 'grievance-filter_priority-field',
    'start_date' => 'grievance-start_date-field',
    'end_date' => 'grievance-end_date-field',
];
